#!/bin/bash

# Start Simple X Hotkey Daemon
sxhkd &

# Load Custom Hotkeys
if [[ -d ~/.config/keysanity ]]; then
	xmodmap ~/.config/keysanity/usVim
	xmodmap ~/.config/keysanity/modRemap
fi

# Increase input rate, decrease delay to input on hold key
[[ -x "$(command -v xset)" ]] && xset r rate 200 50

# Hide mouse cursor after 3 seconds
[[ -x "$(command -v unclutter)" ]] && unclutter --timeout 3 --jitter 75 --ignore-scrolling &

# Compton for terminal transparency and blur
[[ -x "$(command -v compton)" ]] && compton --backend glx --blur-method kawase --blur-strength 5 --blur-background &

# redeemer config
if [[ "$HOSTNAME" == "redeemer" ]]; then
	bspc monitor DisplayPort-0 -d 1 2
	bspc monitor DisplayPort-1 -d 3 4
	bspc monitor HDMI-A-0 -d 5 6
	bspc monitor DisplayPort-2 -d 7 8
	feh --bg-scale ~/Pictures/wallpaper/NodBGScaled/Nod8.jpg
	xinput map-to-output 'Wacom Cintiq Pro 13 Pen Pen (0x8880733e)' DisplayPort-2
	xinput map-to-output 'Wacom Cintiq Pro 13 Touch Finger' DisplayPort-2
	startJACK
	[[ -x "$(command -v polybar)" ]] && polybar -r redeemer & disown

# stealthTank config
elif [[ "$HOSTNAME" == "stealthTank" ]]; then
	bspc monitor eDP1 -d 1 2 3 4 5 6
	feh --bg-scale ~/Pictures/NodBG/Nod4.jpg
	[[ -x "$(command -v polybar)" ]] && polybar -r redeemer & disown

# generic config
else
	bspc monitor -d 1 2 3 4 5 6 7 8 9
fi

#### BSPWM configuration ####
#bspc config border_radius                8
bspc config border_width                  2
bspc config window_gap                    5
bspc config top_padding                   0
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_follows_monitor 	  true
bspc config pointer_modifier 			  mod4
bspc config pointer_action1 			  move
bspc config pointer_action2 			  resize_side
bspc config pointer_action3 			  resize_corner

#### BSPWM coloring ####
bspc config normal_border_color		      "#4c566a"
bspc config active_border_color	          "#1e1e1e"
bspc config focused_border_color	      "#5e81ac"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
xdo below -t "$(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-0)"
xdo below -t "$(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-1)"
xdo below -t "$(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-2)"

bspc rule -a obs monitor='^2' follow=on
bspc rule -a Screenkey manage=off
# bspc rule -a \* state=floating

bspc config ignore_ewmh_fullscreen none
